services:
  caddycontrol:
    image: itbeeazy/caddy-control:1.0.0
    container_name: caddycontrol
    restart: unless-stopped
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production
      - APP_HOST=demo.example.com
      - CADDY_SERVER_IP=127.0.0.1
      - CADDY_ADMIN_URL=http://localhost:2019
      - JWT_SECRET=alksdlaksdjasd
    network_mode: host

